# DEVELOPMENT ONLY, DO NOT USE FOR PRODUCTION
version: '3.5'

services:
  cache:
    container_name: "uala-challenge-test-cache"
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=uala_challenge2024
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
